---
# rule  xccdf_org.ssgproject.content_rule_accounts_minimum_age_login_defs
# Enforcing a minimum password lifetime helps to prevent repeated password changes to defeat the password reuse or history enforcement requirement. If users are allowed to immediately and continually change their password, then the password could be repeatedly changed in a short period of time to defeat the organization's policy regarding password reuse.
#
# Setting the minimum password age protects against users cycling back to a favorite password after satisfying the password reuse requirement.
#
# source https://static.open-scap.org/ssg-guides/ssg-rhel7-guide-rht-ccp.html#xccdf_org.ssgproject.content_rule_accounts_minimum_age_login_defs
- name: Gather the package facts
  package_facts:
    manager: auto
  tags:
    - CCE-82036-5
    - CJIS-5.6.2.1.1
    - DISA-STIG-RHEL-07-010230
    - NIST-800-171-3.5.8
    - NIST-800-53-CM-6(a)
    - NIST-800-53-IA-5(1)(d)
    - NIST-800-53-IA-5(f)
    - accounts_minimum_age_login_defs
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
- name: XCCDF Value var_accounts_minimum_age_login_defs # promote to variable
  set_fact:
    var_accounts_minimum_age_login_defs: !!str 7
  tags:
    - always

- name: Set Password Minimum Age
  lineinfile:
    create: true
    dest: /etc/login.defs
    regexp: ^#?PASS_MIN_DAYS
    line: PASS_MIN_DAYS {{ var_accounts_minimum_age_login_defs }}
  when: '"shadow-utils" in ansible_facts.packages'
  tags:
    - CCE-82036-5
    - CJIS-5.6.2.1.1
    - DISA-STIG-RHEL-07-010230
    - NIST-800-171-3.5.8
    - NIST-800-53-CM-6(a)
    - NIST-800-53-IA-5(1)(d)
    - NIST-800-53-IA-5(f)
    - accounts_minimum_age_login_defs
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
